services:
  postgres-container:
    container_name: postgres
    image: postgres
    ports: 
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/
