services:
  postgres-container:
    container_name: postgres
    image: postgres
    ports: 
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      pg-network:
        aliases:
          - host-postgres 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment: 
      PGADMIN_DEFAULT_EMAIL: "eduardomachado__@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"  
    networks:
      pg-network:
        aliases:
          - host-pgadmin 

networks:
  pg-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/db_data
      o: bind
