services:
  postgres-container:
    container_name: postgres-database
    image: postgres
    command: ["tail", "-f", "/dev/null"]
    ports: 
      - "5433:5432" 
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
